### PR TITLE
test: Add getting started integration test

### PR DESCRIPTION
**Pull request by kriskowal**
This change adds an integration test that verifies that the Agoric SDK CI integration test will pass after any change to the dapp template lands.

Pairs with https://github.com/Agoric/agoric-sdk/pull/3762

### CODE REVIEW

**Comment by katelynsills** [comment]
Is there anything I can help with on this?

**Comment by kriskowal** [comment]
@katelynsills Possibly. The problem I’m stuck on is that the getting started workflow script in Agoric SDK needs to clone dapp-fungible-faucet from the PR branch. I may have wandered down the wrong path in #3762 by trying to clone from the PR’s checkout.

💡 Perhaps I should try just having the CI job clone from github using the PR ref environment variable. I don’t think I’ll have any luck making `yarn integration-test` locally verifiable, but I’m past that point already.

**Comment by kriskowal** [comment]
That did the trick. This is ready to go.

**Review by katelynsills — APPROVED** [review]
The content looks great to me, but can we change the name of the test to make it clear it includes an integration test, or move it out into its own test? I looked at this and wondered where the integration test was, until I realized it was in the same file. 

Screen Shot 2021-08-27 at 4 44 08 PM

**Pull request merged**
